name: Create Prod Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version (ie dd.mm.yy)'
        required: true
jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.NPM_TOKEN }}
          ref: staging
      - name: Create release branch
        run: git checkout -b staging-to-main-release/${{ github.event.inputs.versionName }}-rc
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Update branch in schema path files
        run: |
          # Replace "/staging/" with "/main/" in all schemas
          find examples/**/*.json -type f -exec sed -i -e 's/\/staging\//\/main\//g' {} +
          find examples/**/*.jsonld -type f -exec sed -i -e 's/\/staging\//\/main\//g' {} +
      - name: Prepare commmit
        run: |
          git add .
          git commit -m "Change staging to main branch in schema path files"
      - name: Push new branch
        run: git push origin staging-to-main-release/${{ github.event.inputs.versionName }}-rc
      - name: Create and push a new tag release
        run: |
          git tag -a release/${{ github.event.inputs.versionName }}-rc -m "Release ${{ github.event.inputs.versionName }}-rc"
          git push origin release/${{ github.event.inputs.versionName }}-rc
      - name: Create pull request into main branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: staging-to-main-release/${{ github.event.inputs.versionName }}-rc
          base: main
          title: release/${{ github.event.inputs.versionName }}-rc into main
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
