name: Deploy prod schemas

on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
        description: Commit SHA
      pull-request-number:
        required: true
        type: string
        description: Pull request number
      branch:
        required: true
        type: string
        description: Branch

jobs:
  release:
    name: Apply schemas
    runs-on: ubuntu-latest
    env:
      ENV: prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload schemas to Polygon issuer
        shell: bash
        run: |
          for file in $(find ipfs/ -type f -name "*.json"); do
            echo "JSON file: $file"
            version=$(cat "$file" | jq -r '.["$metadata"].version')
            echo "$version"

            schema=$(cat "$file" | jq -r '.["$metadata"].type')
            echo "$schema"

            curl -X POST "https://mumbai-issuer-node-prod.nexera.id/v1/schemas" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -u "${{ secrets.ISSUER_NODE_USERNAME_PROD }}:${{ secrets.ISSUER_NODE_PASSWORD_PROD }}" \
              -d "{\"url\":\"https://raw.githubusercontent.com/NexeraProtocol/vc-schemas/main/${file}\",\"schemaType\":\"${schema}\",\"version\":\"${version}\"}"

            curl -X POST "https://issuer-node.nexera.id/v1/schemas" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -u "${{ secrets.ISSUER_NODE_USERNAME_PROD_MAINNET }}:${{ secrets.ISSUER_NODE_PASSWORD_PROD_MAINNET }}" \
              -d "{\"url\":\"https://raw.githubusercontent.com/NexeraProtocol/vc-schemas/main/${file}\",\"schemaType\":\"${schema}\",\"version\":\"${version}\"}"
          done
