name: Deploy schemas from branch

on:
  workflow_dispatch:
    inputs:
      issuer:
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        description: Polygon issuer
        default: dev
      branch:
        required: true
        type: string
        description: Branch name

jobs:
  release:
    name: Apply schemas
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.MERGE_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: ${{ inputs.branch }}

      - name: Initialize git config
        run: |
          git config --global user.name "nexera-release[bot]"
          git config --global user.email "137495321+nexera-release[bot]@users.noreply.github.com"

      - name: Install dependencies
        shell: bash
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version

      - name: Get current version
        id: versions
        shell: bash
        run: |
          timestamp=$(date +%s%3N)
          
          current=$(cat polygon-id/id3/id3.json | jq -r '.["$metadata"].version')
          target="$current-${{ inputs.branch }}-$timestamp"

          echo "$current"
          echo "$target"

          echo "current=$current" >> $GITHUB_OUTPUT
          echo "target=$target" >> $GITHUB_OUTPUT

      - name: Find and replace Polygon ID versions
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ steps.versions.outputs.current }}
          replace: ${{ steps.versions.outputs.target }}
          include: "polygon-id/**"

      - name: Copy schemas to IPFS directory
        continue-on-error: true
        shell: bash
        run: |
          rm -rf ipfs/
          mkdir ipfs
          touch ipfs/.gitkeep
          cp -r polygon-id/* ipfs/
          ls -al ipfs/
          ls -R ipfs/

      - name: Upload jsonID to IPFS and replace uris with hash in json schemas
        shell: bash
        run: |
          # Find all jsonLD files in the ipfs/ folder
          for file in $(find ipfs/ -type f -name "*.jsonld"); do
            echo "JsonLD file: $file"

            # Upload json
            response=$(curl "https://ipfs.infura.io:5001/api/v0/add" -X POST -F file=@"$file" -u "${{ secrets.INFURA_IPFS_API_KEY }}:${{ secrets.INFURA_IPFS_API_KEY_SECRET }}")
            echo "$response"

            # Parse HASH from uploaded file
            ipfs_hash=$(echo "$response" | jq -r '.Hash')
            echo "$ipfs_hash"

            # Set the json file path
            replacement=".json"
            json_file_path="${file/.jsonld/$replacement}"
            echo "JSON file: $json_file_path"

            # Perform update
            jq '.["$metadata"].uris.jsonLdContext = "ipfs://'"$ipfs_hash"'"' "$json_file_path" > temp.json && mv temp.json "$json_file_path"
          done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ inputs.branch }}
          message: 'chore: Update IPFS schemas [skip ci]'
          author_name: 'nexera-release[bot]'
          author_email: '137495321+nexera-release[bot]@users.noreply.github.com'

      - name: Upload schemas to issuer (mumbai)
        shell: bash
        run: |
          issuer="https://mumbai-issuer-node-dev.nexera.id/v1/schemas"
          if [ ${{ inputs.issuer }} == 'staging' ]; then
            issuer="https://mumbai-issuer-node-staging.nexera.id/v1/schemas"
          elif [ ${{ inputs.issuer }} == 'prod' ]; then
            issuer="https://mumbai-issuer-node-prod.nexera.id/v1/schemas"
          fi
          
          for file in $(find ipfs/ -type f -name "*.json"); do
            echo "JSON file: $file"
            version=$(cat "$file" | jq -r '.["$metadata"].version')
            echo "$version"

            schema=$(cat "$file" | jq -r '.["$metadata"].type')
            echo "$schema"

            curl -X POST "$issuer" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -u "${{ secrets.ISSUER_NODE_USERNAME_PROD }}:${{ secrets.ISSUER_NODE_PASSWORD_PROD }}" \
              -d "{\"url\":\"https://raw.githubusercontent.com/NexeraProtocol/vc-schemas/${{ inputs.branch }}/${file}\",\"schemaType\":\"${schema}\",\"version\":\"${version}\"}"
          done

      - name: Upload schemas to issuer (mainnet)
        if: ${{ inputs.issuer == 'prod' }}
        shell: bash
        run: |
          for file in $(find ipfs/ -type f -name "*.json"); do
            echo "JSON file: $file"
            version=$(cat "$file" | jq -r '.["$metadata"].version')
            echo "$version"

            schema=$(cat "$file" | jq -r '.["$metadata"].type')
            echo "$schema"

            curl -X POST "https://issuer-node.nexera.id/v1/schemas" \
              -H "accept: application/json" \
              -H "content-type: application/json" \
              -u "${{ secrets.ISSUER_NODE_USERNAME_PROD_MAINNET }}:${{ secrets.ISSUER_NODE_PASSWORD_PROD_MAINNET }}" \
              -d "{\"url\":\"https://raw.githubusercontent.com/NexeraProtocol/vc-schemas/${{ inputs.branch }}/${file}\",\"schemaType\":\"${schema}\",\"version\":\"${version}\"}"
          done

      - name: Go back one commit
        continue-on-error: true
        shell: bash
        run: |
          git remote -v
#          git config --global user.name "nexera-release[bot]"
#          git config --global user.email "137495321+nexera-release[bot]@users.noreply.github.com"
#          git reset --hard HEAD~1
#          git push --force origin ${{ inputs.branch }}

      - name: Undo last push
        uses: exions/undo-push@v1
        with:
          branch: ${{ inputs.branch }}
